local mod = "SUPER"

hl.bind(mod .. " + CTRL + RETURN", hl.dsp.global("quickshell:appLauncher"))
hl.bind(mod .. " + grave",         hl.dsp.global("quickshell:overview"))
hl.bind(mod .. " + W",             hl.dsp.global("quickshell:wallpaperLauncher"))
hl.bind(mod .. " + S",             hl.dsp.global("quickshell:toolsWidget"))
hl.bind(mod .. " + V",             hl.dsp.global("quickshell:clipboard"))
hl.bind(mod .. " + SHIFT + V",     hl.dsp.global("quickshell:clipboardPocket"))
hl.bind(mod .. " + CTRL + S",      hl.dsp.global("quickshell:settingOpen"))
hl.bind(mod .. " + slash",         hl.dsp.global("quickshell:cheatsheet"))
hl.bind(mod .. " + SHIFT + F",     hl.dsp.global("quickshell:filedrop"))
hl.bind(mod .. " + O",             hl.dsp.global("quickshell:ocr"))
hl.bind(mod .. " + A",             hl.dsp.global("quickshell:pie"))
hl.bind(mod .. " + X",             hl.dsp.global("quickshell:tuck"))
hl.bind(mod .. " + SHIFT + X",     hl.dsp.global("quickshell:untuck"))
hl.bind(mod .. " + F1",            hl.dsp.global("quickshell:spotlight"))
hl.bind(mod .. " + N",             hl.dsp.global("quickshell:note"))
hl.bind(mod .. " + L",             hl.dsp.global("quickshell:lock"),     { locked = true })
hl.bind(mod .. " + SHIFT + S",     hl.dsp.global("quickshell:shutdown"), { locked = true })
