pragma Singleton
pragma ComponentBehavior: Bound

import Quickshell
import Quickshell.Io
import QtQuick
import qs.modules.settings

// Owns ~/.config/hypr/hypridle.conf: the settings page edits timeouts, this
// regenerates the file and restarts hypridle so the change takes effect now
// rather than at next login.
//
// The file is generated wholesale rather than patched, because hypridle has no
// include mechanism to keep hand-written and generated parts apart. A one-time
// backup is taken the first time this writes, so the original hand-tuned config
// is always recoverable from hypridle.conf.bak.
Singleton {
    id: root

    readonly property string confPath: Quickshell.env("HOME") + "/.config/hypr/hypridle.conf"
    readonly property string backupPath: root.confPath + ".bak"

    readonly property var cfg: SettingsConfig.sleep

    // Minutes in settings; hypridle wants seconds
    function _secs(min) { return Math.max(1, Math.round((min ?? 1) * 60)) }

    function buildConf() {
        var out = ""
        out += "# Generated by quickshell — Settings › Sleep\n"
        out += "# Hand edits here are overwritten. Original saved as hypridle.conf.bak\n\n"

        out += "general {\n"
        out += "    lock_cmd = hyprctl dispatch global quickshell:lock\n"
        out += "    before_sleep_cmd = loginctl lock-session\n"
        out += "    after_sleep_cmd = hyprctl dispatch dpms on\n"
        out += "}\n"

        if (root.cfg?.dimEnabled ?? true) {
            out += "\n# Dim the backlight\n"
            out += "listener {\n"
            out += "    timeout = " + root._secs(root.cfg?.dimMinutes) + "\n"
            out += "    on-timeout = brightnessctl -s set " + (root.cfg?.dimLevel ?? 10) + "\n"
            out += "    on-resume = brightnessctl -r\n"
            out += "}\n"
        }

        if (root.cfg?.lockEnabled ?? true) {
            out += "\n# Lock the session\n"
            out += "listener {\n"
            out += "    timeout = " + root._secs(root.cfg?.lockMinutes) + "\n"
            out += "    on-timeout = loginctl lock-session\n"
            out += "}\n"
        }

        if (root.cfg?.screenOffEnabled ?? false) {
            out += "\n# Turn the display off\n"
            out += "listener {\n"
            out += "    timeout = " + root._secs(root.cfg?.screenOffMinutes) + "\n"
            out += "    on-timeout = hyprctl dispatch dpms off\n"
            out += "    on-resume = hyprctl dispatch dpms on && brightnessctl -r\n"
            out += "}\n"
        }

        if (root.cfg?.suspendEnabled ?? true) {
            out += "\n# Suspend\n"
            out += "listener {\n"
            out += "    timeout = " + root._secs(root.cfg?.suspendMinutes) + "\n"
            out += "    on-timeout = systemctl suspend\n"
            out += "}\n"
        }

        return out
    }

    // ── Write + reload ────────────────────────────────────────────────
    FileView {
        id: confFile
        path: root.confPath
        printErrors: true
    }

    function apply() {
        // cp -n never clobbers an existing backup, so the very first generated
        // write is the only one that can create it.
        Quickshell.execDetached(["sh", "-c",
            "cp -n '" + root.confPath + "' '" + root.backupPath + "' 2>/dev/null || true"])
        confFile.setText(root.buildConf())
        restartTimer.restart()
    }

    // hypridle re-reads its config only on start, so it has to be replaced.
    // Delayed so the write lands first.
    Timer {
        id: restartTimer
        interval: 250
        repeat: false
        onTriggered: Quickshell.execDetached(["sh", "-c",
            "pkill -x hypridle; sleep 0.2; hypridle & disown"])
    }

    // Debounced so dragging a spin box doesn't restart hypridle per step
    Timer {
        id: debounce
        interval: 700
        repeat: false
        onTriggered: root.apply()
    }

    // Deliberately not applied on startup — that would rewrite the user's
    // config just because the shell launched. Only an actual settings change
    // regenerates the file.
    property bool _armed: false
    onCfgChanged: {
        if (!root._armed) { root._armed = true; return }
        debounce.restart()
    }
}
