pragma Singleton
pragma ComponentBehavior: Bound

import Quickshell
import Quickshell.Io
import Quickshell.Wayland
import QtQuick
import qs.modules.utils

// Parses the launcher query into a mode + term and produces the results for
// every non-app mode. App mode stays in ServiceApps and keeps its own
// DesktopEntry-shaped model, because the app list needs pinning, categories
// and the context menu that a normalised result object can't carry.
//
// Results here are normalised to:
//   { key, title, subtitle, glyph, symbol, iconName, payload, action }
// where `action` is one of "copy" | "run" | "run-term" | "focus", and `payload`
// is what that action consumes. The views stay dumb; activate() does the work.
Singleton {
    id: root

    // ── Mode table ────────────────────────────────────────────────────────────
    readonly property var modes: [
        { id: "calc",    prefix: "=", label: "Calc",    icon: "calculate",     hint: "1920*0.15 · 100 usd to inr" },
        { id: "run",     prefix: ">", label: "Run",     icon: "terminal",      hint: "shell command" },
        { id: "emoji",   prefix: ":", label: "Emoji",   icon: "mood",          hint: "fire · rocket · thumbsup" },
        { id: "windows", prefix: "w", label: "Windows", icon: "select_window", hint: "open windows" }
    ]

    // `w` is a bare letter, so it only counts as a prefix when followed by a
    // space — otherwise "wezterm" would never reach app search.
    function _prefixOf(q) {
        if (q.length === 0) return null
        for (const m of root.modes) {
            if (m.prefix === "w") {
                if (q === "w " || q.startsWith("w ")) return m
            } else if (q.startsWith(m.prefix)) {
                return m
            }
        }
        return null
    }

    property string query: ""

    readonly property var activeMode: _prefixOf(query)
    readonly property string mode: activeMode ? activeMode.id : "apps"
    readonly property string term: {
        if (!activeMode) return query
        return query.slice(activeMode.prefix.length).trim()
    }

    property var results: []

    onQueryChanged: _recompute()

    function _recompute() {
        switch (root.mode) {
        case "calc":    calcDebounce.restart();     break
        case "run":     results = _runResults();    break
        case "emoji":   results = _emojiResults();  break
        case "windows": results = _windowResults(); break
        default:        results = []
        }
    }

    // ── Calculator (qalc) ─────────────────────────────────────────────────────
    // qalc always exits 0 and always prints something, so there is no error
    // channel to test — a nonsense expression just yields a nonsense result.
    // The view shows whatever came back and lets the user judge it.
    property string calcResult: ""

    Timer {
        id: calcDebounce
        interval: 120
        onTriggered: {
            if (root.term.length === 0) {
                root.calcResult = ""
                root.results = []
                return
            }
            calcProc.running = false
            calcProc.command = ["qalc", "-t", "-e", root.term]
            calcProc.running = true
        }
    }

    Process {
        id: calcProc

        stdout: StdioCollector {
            onStreamFinished: {
                // A stale result can land after the user has switched modes.
                if (root.mode !== "calc") return

                root.calcResult = text.trim()
                root.results = root.calcResult.length > 0
                    ? [{
                        key: "calc",
                        title: root.calcResult,
                        subtitle: root.term,
                        glyph: "",
                        symbol: "calculate",
                        iconName: "",
                        payload: root.calcResult,
                        action: "copy"
                    }]
                    : []
            }
        }
    }

    // ── Run ───────────────────────────────────────────────────────────────────
    readonly property string terminal: Quickshell.env("TERMINAL") || "kitty"

    function _runResults() {
        if (root.term.length === 0) return []
        return [
            {
                key: "run",
                title: root.term,
                subtitle: "Run command",
                glyph: "", symbol: "terminal", iconName: "",
                payload: root.term,
                action: "run"
            },
            {
                key: "run-term",
                title: root.term,
                subtitle: "Run in " + root.terminal + ", keep output open",
                glyph: "", symbol: "dock_to_bottom", iconName: "",
                payload: root.term,
                action: "run-term"
            }
        ]
    }

    // ── Emoji ─────────────────────────────────────────────────────────────────
    // Data generated by scripts/gen_emoji.py. The JSON parse is cheap, but
    // Fuzzy.prepare over ~1500 entries is not, so that part stays lazy — same
    // approach as ServiceApps._ensurePrepared().
    property var _emoji: []
    property var _emojiPrepped: null

    FileView {
        id: emojiFile
        path: Quickshell.env("HOME") + "/.config/quickshell/assets/emoji.json"
        onLoaded: {
            try {
                root._emoji = JSON.parse(text())
            } catch (e) {
                console.warn("[ServiceLauncher] could not parse emoji.json:", e)
                root._emoji = []
            }
            root._emojiPrepped = null
        }
        onLoadFailed: {
            console.warn("[ServiceLauncher] emoji.json missing — run scripts/gen_emoji.py")
            root._emoji = []
        }
    }

    function _ensureEmojiPrepared() {
        if (!root._emojiPrepped)
            root._emojiPrepped = root._emoji.map(e => ({ kw: Fuzzy.prepare(e.kw), item: e }))
        return root._emojiPrepped
    }

    function _emojiPick(list) {
        return list.map(e => ({
            key: "emoji-" + e.ch,
            title: e.ch,
            subtitle: e.name,
            glyph: e.ch,
            symbol: "", iconName: "",
            payload: e.ch,
            action: "copy"
        }))
    }

    function _emojiResults() {
        if (root._emoji.length === 0) return []
        if (root.term.length === 0) return _emojiPick(root._emoji.slice(0, 200))

        return _emojiPick(
            Fuzzy.go(root.term, _ensureEmojiPrepared(), { all: true, key: "kw", limit: 200 })
                .map(r => r.obj.item)
        )
    }

    // ── Windows ───────────────────────────────────────────────────────────────
    function _windowResults() {
        const wins = Array.from(ToplevelManager.toplevels.values)
            .filter(t => (t.appId ?? "").length > 0)

        const needle = root.term.toLowerCase()
        const matched = needle.length === 0 ? wins : wins.filter(t => {
            return ((t.appId ?? "") + " " + (t.title ?? "")).toLowerCase().includes(needle)
        })

        return matched.map((t, i) => ({
            key: "win-" + i + "-" + (t.appId ?? ""),
            title: (t.title && t.title.length > 0) ? t.title : t.appId,
            subtitle: t.appId,
            glyph: "", symbol: "select_window",
            iconName: t.appId,
            payload: t,
            action: "focus"
        }))
    }

    // ── Activation ────────────────────────────────────────────────────────────
    // Returns true when the launcher should close.
    function activate(result): bool {
        if (!result) return false

        switch (result.action) {
        case "copy":
            Quickshell.clipboardText = result.payload
            return true

        case "run":
            Quickshell.execDetached(["bash", "-lc", result.payload])
            return true

        case "run-term":
            Quickshell.execDetached([
                root.terminal, "-e", "bash", "-lc",
                result.payload + "; echo; read -n1 -r -p 'press any key…'"
            ])
            return true

        case "focus":
            if (result.payload) result.payload.activate()
            return true
        }
        return false
    }

    function reset() {
        root.query = ""
        root.results = []
        root.calcResult = ""
    }
}
