require("lua.environment")
require("lua.monitor")
require("lua.autostart")
require("lua.settings")
require("lua.animations")
require("lua.keybinds")
require("lua.rules")

require("nebula.environment")
require("nebula.autostart")
require("nebula.keybinds")
require("nebula.rules")
