cursor            #ebe0df
cursor_text_color #4e2425

foreground            #ebe0df
background            #120d0d
selection_foreground  #d2b0b0
selection_background  #5c4343
url_color             #f8b6b6

color0  #3f3232
color8  #948282

color1  #fe8989
color9  #ffbbb9

color2  #87b95b
color10 #a0dd69

color3  #ffb226
color11 #ffddb1

color4  #9ea3ff
color12 #c6c8ff

color5  #ea8cce
color13 #ffb6e6

color6  #2eb9e4
color14 #74d8ff

color7  #dcc7c7
color15 #ffedec

active_tab_foreground   #4e2425
active_tab_background   #f8b6b6
inactive_tab_foreground #d6c2c1
inactive_tab_background #2e2928

active_border_color   #f8b6b6
inactive_border_color #514343
